### ISSUE TITLE
file name of gmaps-autocomplete.js is wrong

### ISSUE THREAD

**Issue by woyzeck** [kristianmandrup/gmaps-autocomplete-rails#12]
Sorry if this issue might be stupid, but I'm quite new to rails.

I can't get it to run, and after investigating into the issue I think that the file 'vendor/assets/gmaps-autocomplete.js' is missing in the gem.

The file seems to be named 'gmaps-auto-complete.js'

**Comment by theasteve** [comment]
@woyzeck It didn't work for me.  I have in the application.js
```//= require gmaps-autocomplete```
application.scss
```*= require gmaps-autocomplete```
Gemfile
```gem 'gmaps-autocomplete-rails', :git => "https://github.com/kristianmandrup/gmaps-autocomplete-rails.git"```

I get the following error:

couldn't find file 'gmaps-autocomplete' with type 'text/css'

**Comment by onerinas** [comment]
@theasteve Please try `require gmaps-auto-complete`
