### ISSUE TITLE
How to use Google Places API Key?

### ISSUE THREAD

**Issue by stefanocdn** [kristianmandrup/gmaps-autocomplete-rails#17]
Hi, I read the documentation but cannot find a way to use a Google API Key (to increase the number of requests), is there a way to do it?

I know I could add key param inside the URL

`<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=XXXX&amp;sensor=false"></script>`

But is that safe to embed an API Key on the client side?

**Comment by kristianmandrup** [comment]
Read the Google API docs ;) 

```
<script async defer src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
  type="text/javascript"></script>
```

You now *have to* use HTTPS, to ensure it is safe and the key (and your location?) is not intercepted.
